#! /bin/sh

case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac

# possible languages c,c++,d,fortran,go,objc,obj-c++
cd gcc                                                 &&
mkdir build                                            &&
cd    build                                            &&
../configure                                           \
    --prefix=/usr                                      \
    --disable-multilib                                 \
    --with-system-zlib                                 \
    --enable-languages=c                               &&
make