#! /bin/sh

# Vriy big job:
# apt-get build-dep llvm-9
# apt-get source llvm-9
# cd ./llvm-toolchain-9-9/
# dpkg-buildpackage -us -uc

###############

apt-get build-dep -y  gcc-8-x86-64-linux-gnux32
apt-get source  gcc-8-x86-64-linux-gnux32
cd ./gcc-8-cross-ports-9ubuntu0.5/
dpkg-buildpackage -us -uc

echo "neue Release"